### ISSUE TITLE
can't open executable file

### ISSUE THREAD

**Issue by jackthenewbie** [yumiris/Gunloader#2]
like the title said, I'm on win10 21h1 19043.1165

**Comment by yumiris** [comment]
Any particular errors? Feel free to take a screenshot of anything that pops up -- it'll help a lot!

**Comment by jackthenewbie** [comment]
> Any particular errors? Feel free to take a screenshot of anything that pops up -- it'll help a lot!

ye sorry, my head wasn't clear last night. I think I misread the readme, but now I'm not really understand how can I download music as flac there. So I thought If I just download the zipfile gunloader for windows, open gunloader.exe and thing would work, but it don't. A cmd window popup and close immediately. Can you help me what I have done wrong? Thanks.

**Comment by yumiris** [comment]
Ah, it's because Gunloader has to be run *using* CMD (open up CMD, run Gunloader from there). However, I'm working on a GUI for it to make it a bit more intuitive to use. Cheers for the patience and feedback!

**Comment by yumiris** [comment]
@jackthenewbie [v0.7.4](https://github.com/yumiris/Gunloader/releases/tag/v0.7.4) should hopefully solve this. Feel free to let me know if you encounter any issues or confusions.

**Comment by jackthenewbie** [comment]
@yumiris thanks things work now:)
